# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89b25da1d6c4550a5bce9f795f0500493cedacc4a6d02ea63062bb6fe3bb97683e10373f61c9c7d72411d0ee3e8ce5c4aa78a2c20fdc90416c05c55bb638fc96

test:
  secret_key_base: 0dcdfa8f651571dd152450ba8d91f660c8fdec323c3cb567e96ea25590c230837a0c52472a42457d745ea07c95f737862503423d89190ec80cdf511b980edc83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
